[build]
  # 发布目录
  publish = "netlify-deploy"
  
  # 构建命令(我们不需要构建,直接发布静态文件)
  command = "echo 'No build needed'"

# 重定向规则(可选)
[[redirects]]
  from = "/"
  to = "/escape.html"
  status = 200

# 头部设置(可选,用于缓存优化)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
[[headers]]
  for = "/escape.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

